### ISSUE TITLE
Reverse direction of volume up/down on bigKNOBv2

### ISSUE THREAD

**Issue by loganmarchione** [LeafCutterLabs/bigKNOB#1]
I just purchased the bigKNOBv2 and noticed the direction of volume up/down on the knob was reversed.

In my mind, turning the knob clockwise should be "volume up" and counter-clockwise is "volume down" (like the image below).  
https://cdn3.vectorstock.com/i/1000x1000/60/12/volume-button-knob-vector-1866012.jpg

The code would seem to suggest this is correct, but it's backwards. I switched lines 8 and 10 in this file and it seems to be "right" to me. Can you confirm?  
https://github.com/LeafCutterLabs/bigKNOB/blob/master/Software/QMKv2/keymaps/default/keymap.c

**Comment by LeafCutterLabs** [comment]
That is correct but depends on the brand of encoder (Alps is different than
Bourns).

**Comment by loganmarchione** [comment]
Got it, thanks!
