### ISSUE TITLE
bigKNOB not showing up on the menu of keyboards in QMK

### ISSUE THREAD

**Issue by waterswrld** [LeafCutterLabs/bigKNOB#2]
I just bought a bigKNOB but the name for it is not showing up in QMK configurator. What should I do?

**Comment by LeafCutterLabs** [comment]
QMK configurator does not currently support rotary encoders so you will
have to compile yourself. If you have troubles compiling feel free to email
me your keymap and I can compile/send the hex.

**Comment by waterswrld** [comment]
I've only never used QMK until now so if you could help me out that would be great. I'm not sure I have my own keymap tho

**Comment by LeafCutterLabs** [comment]
Email me at leafcutterlabs@gmail.com with what you want it to do e.g. knob
controls volume, knob button mutes, 1st button F13, 2nd button A, 3rd
button ctrl Z, etc.
